AWSTemplateFormatVersion: '2010-09-09'
Description: Lowest cost EC2 using CloudFormation (Free Tier)

Parameters:
  KeyName:
    Description: EC2 KeyPair for SSH
    Type: AWS::EC2::KeyPair::devops-project-key

Resources:
  LowCostEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: CFN-Low-Cost-EC2

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref LowCostEC2
